apiVersion: ec2.aws.crossplane.io/v1beta1
kind: RouteTable
metadata:
  name: private-route-table
spec:
  forProvider:
    vpcIdSelector:
      matchControllerRef: true
    routes:
      - cidrBlock: "0.0.0.0/0"
        natGatewayIdSelector:
          matchControllerRef: true
    tags:
      - key: Environment
        value: dev
      - key: Name
        value: private-route-table
  providerConfigRef:
    name: aws-provider
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: private-subnet-1a-rta
spec:
  forProvider:
    subnetIdSelector:
      matchLabels:
        Name: private-subnet-1a
    routeTableIdSelector:
      matchControllerRef: true
  providerConfigRef:
    name: aws-provider
---
apiVersion: ec2
