apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: main-vpc
spec:
  forProvider:
    cidrBlock: "10.0.0.0/16"
    enableDnsSupport: true
    enableDnsHostnames: true
  providerConfigRef:
    name: default
  tags:
    - key: Name
      value: "main-vpc"
    - key: Project
      value: "<project_name>"
    - key: Region
      value: "<region>"
